spring.application.name=dropzone

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
SUPABASE_BUCKET=${SUPABASE_BUCKET}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB